[package]
name = "radix_sort"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rayon = "1.5.1"
itertools = "0.10.3"

[profile.release]
opt-level = 3